FROM mambaorg/micromamba:1.5.8

USER root
RUN apt-get update && apt-get install -y --no-install-recommends curl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY umap-service/environment.yml .
RUN micromamba env create -y -f environment.yml && \
    micromamba clean --all --yes

COPY umap-service/ .

EXPOSE 8000
CMD ["micromamba", "run", "-n", "spotify-project", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
